### ISSUE TITLE
Displaying serverless map tiles in TerriaMap

### ISSUE THREAD

**Issue by rsignell-usgs** [kylebarron/usgs-topo-mosaic#4]
@kylebarron ,  I did a test trying to display the serverless map tiles in [TerriaJS](https://github.com/TerriaJS/terriajs/blob/master/README.md) (see [interactive demo](https://map.terria.io/#share=s-g2J5VdGvGEiy3XN19nyCAz0mPK2&playStory=1) if interested), using this "url-template" catalog that @kring supplied me:
```json
{
  "catalog": [
    {
      "name": "USGS TopoMap Test",
      "type": "url-template",
            "url": "https://us-west-2-lambda.kylebarron.dev/usgs-topo/{z}/{x}/{y}@2x.jpg?url=dynamodb%3A%2F%2Fus-west-2%2Fusgs-topo_high_oldest.v2"
        }
    ]
}
```
Which one can visualize using:
https://gamone.whoi.edu/terriamap/#clean&proxy/_60s/https://raw.githubusercontent.com/USGS-CMG/terriajs-dive/master/examples/topo_template.json

And while this mostly works (hurrah!):
![2020-06-25_8-34-19](https://user-images.githubusercontent.com/1872600/85721273-36a4cc00-b6bf-11ea-8365-ef8e198c7f3c.png)

generating requests like: 
https://gamone.whoi.edu/terriamap/proxy/https://us-west-2-lambda.kylebarron.dev/usgs-topo/12/1249/1524@2x.jpg?url=dynamodb%3A%2F%2Fus-west-2%2Fusgs-topo_high_oldest.v2

we find that after a bit of panning/zooming around we get errors like this: 
![2020-06-25_8-40-02](https://user-images.githubusercontent.com/1872600/85721709-9d29ea00-b6bf-11ea-944f-d0dafc803667.png)

I guess this could be a feature rather than a bug to prevent overuse or something, but I thought I should report out here with what I found in case others try something like this.

**Comment by kylebarron** [comment]
I think you're hitting my CORS settings 🙂 

Since the example is hosted on my own AWS account, I define a [set of allowed origins](https://github.com/kylebarron/usgs-topo-mosaic/blob/e4699e8c7938295a6cd402b25915d0f607a782a8/serverless.kyle.yml#L10-L39) for my hosted version, basically so that someone doesn't launch a high-traffic website pointing to my server.

But this is designed to be really easy to deploy yourself; make sure you have Docker and `serverless` installed, then essentially just
```
make package && sls deploy --bucket your-bucket-in-us-west-2
```
Then you just replace
```
https://us-west-2-lambda.kylebarron.dev/usgs-topo/
```
with whatever endpoint url is printed at the end of the previous command.

**Comment by kylebarron** [comment]
Note also that the `url` query parameter used in my example points to a DynamoDB database on my account. To get started, you can just change that to a public mosaic in `usgs-topo-tiler`:
```
https://raw.githubusercontent.com/kylebarron/usgs-topo-tiler/master/data/mosaic_high_oldest_v1.json.gz
```

**Comment by rsignell-usgs** [comment]
Thanks @kylebarron !   I'm heading out for a week of vacay, but will try setting this up on our account when I return!
